### ISSUE TITLE
Bad vaccination certificate order in detail view

### ISSUE THREAD

**Issue by G00fY2** [Digitaler-Impfnachweis/covpass-android#142]
## Technical details

- Device name: Pixel 4a
- OS version: Android 12
- App version: CovPass 1.13.3 (679)

## Describe the bug

My certificates where added in this order by my local pharmacy:
2. vaccination, 3. vaccination (booster), 1. vaccination (because we detected that the first certificate was missing)

The result looks like this (which can be confusing):
![Screenshot_20211213-182440](https://user-images.githubusercontent.com/1990806/145860859-c5984dce-10b2-4fd7-9b87-62cb7168381d.png)

## Expected behaviour
I would expect the vaccination certificate ordered in the order of the vaccation date (ascending or descending).

For example this is how it looks in the CWA (certificates where added in the same order as in the CovPass App):
![Screenshot_20211213-182515](https://user-images.githubusercontent.com/1990806/145861070-499bf4df-77fa-48f9-819c-e990f60613b8.png)

## Possible Fix

Change the order of displayed vaccination certificates to use the actual date of the vaccination.

**Comment by oliver-steinbrecher** [comment]
The ordering of the list aligned cross CovPass and CWA - This seems to be a bug @alexcimander please pick it up

**Comment by alexcimander** [comment]
Hey everyone,

thank you for pointing it out @G00fY2! 👍 

@oliver-steinbrecher I picked it up! We will provide an update on that soon.

Thank you!

**Comment by Karl-WE** [comment]
@G00fY2 can you confirm it's fixed in Version 1.17?

**Comment by G00fY2** [comment]
@Karl-WE  unfortunately it still looks like on the screenshot I posted from version 1.13.3.

**Comment by G00fY2** [comment]
@Karl-WE @alexcimander this issue is still present with 1.18.0.

**Comment by G00fY2** [comment]
Still not fixed with 1.19.0.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
